import { Metadata } from "next";
import { getCharacters } from "@/utils/api";
import Card from "./Card";

export const metadata: Metadata = {
  title: "Services",
  description: "Generated by create next app",
};

export default async function Services() {
  const characters = await getCharacters();
  // const datas = await getEntries();
  // console.log(characters.data);
  // console.log(characters.results[0].stories);

  return (
    <>
      <div className="text-center py-3">
        <h3 className="text-2xl font-semibold backdrop-blur-sm">
          HERE OUR BEST CUSTOM FIGURE CHARACTERS
        </h3>
      </div>

      {/* CONTENT */}
      <div className="grid lg:grid-cols-4 md:grid-cols-3 grid-cols-2 mx-auto  ">
        {characters.results.map((character) => (
          <Card key={character.id} character={character} />
        ))}
      </div>
    </>
  );
}
